/* Generated By:JavaCC: Do not edit this line. RyzGrammarConstants.java */
package ryzgram;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface RyzGrammarConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int ID = 5;
  /** RegularExpression Id. */
  int NUM = 6;
  /** RegularExpression Id. */
  int ASSIGN = 7;
  /** RegularExpression Id. */
  int IFSY = 8;
  /** RegularExpression Id. */
  int ELSESY = 9;
  /** RegularExpression Id. */
  int WHILESY = 10;
  /** RegularExpression Id. */
  int THENSY = 11;
  /** RegularExpression Id. */
  int PROGRAMSY = 12;
  /** RegularExpression Id. */
  int ENDSY = 13;
  /** RegularExpression Id. */
  int VARSY = 14;
  /** RegularExpression Id. */
  int PRINTSY = 15;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<ID>",
    "<NUM>",
    "\"=\"",
    "\"if\"",
    "\"else\"",
    "\"while \"",
    "\"then\"",
    "\"program\"",
    "\"end\"",
    "\"var\"",
    "\"print\"",
    "\";\"",
    "\"{\"",
    "\"}\"",
    "\" { \"",
    "\" }\"",
    "\"(\"",
    "\")\"",
    "\"<\"",
    "\"==\"",
    "\">\"",
    "\"+\"",
    "\"*\"",
  };

}
